#!/usr/bin/env python3
"""Portfolio summary from the newest snapshot: what is held, how it is spread
across issuers, rating buckets and remaining tenure, the value-weighted YTM,
and which of the profile's limits are breached.

    python3 scripts/portfolio.py [--root PATH]

Writes data/skill-data/PORTFOLIO.md and prints the same summary as JSON.
Ratings come from bond-facts.json; a holding with no recorded rating is shown
as unrated and listed for research. Issuers recorded there under one group (a
parent and its subsidiary) are counted together against the issuer cap."""
import argparse
import json
import os
import sys

import bond_facts
import common


def rating_bucket(rating):
    return rating.rstrip("+-") if rating else "unrated"


def tenure_bucket(months):
    if months is None:
        return "unknown"
    if months < 12:
        return "under 12m"
    if months < 24:
        return "12-24m"
    if months < 36:
        return "24-36m"
    return "over 36m"


def _members(positions, by_issuer):
    for name, share in by_issuer.items():
        members = sorted({p["issuer"] for p in positions if p["group"] == name})
        if members != [name]:
            share["members"] = members
    return by_issuer


def _shares(positions, key, total):
    groups = {}
    for p in positions:
        groups[p[key]] = groups.get(p[key], 0) + p["value"]
    return {name: {"value": round(value, 2),
                   "share_pct": round(100 * value / total, 2) if total else 0.0}
            for name, value in sorted(groups.items(), key=lambda kv: -kv[1])}


def summarise(snapshot, facts, profile):
    held = [h for h in snapshot["holdings"] if (h["current_value"] or 0) > 0]
    total = sum(h["current_value"] for h in held)
    positions = []
    for h in held:
        fact = bond_facts.lookup(facts, isin=h["isin"]) or {}
        months = (common.months_between(snapshot["as_of"], h["maturity_date"])
                  if h["maturity_date"] else None)
        positions.append({
            "issuer": h["issuer"], "isin": h["isin"], "value": h["current_value"],
            "share_pct": round(100 * h["current_value"] / total, 2), "ytm": h["ytm"],
            "months_left": months, "maturity_date": h["maturity_date"],
            "rating": fact.get("rating"), "rating_scope": fact.get("rating_scope"),
            "group": fact.get("group") or bond_facts.group_of(facts, h["issuer"]),
            "bucket": rating_bucket(fact.get("rating")), "tenure": tenure_bucket(months)})
    positions.sort(key=lambda p: -p["value"])
    with_ytm = [p for p in positions if p["ytm"] is not None]
    weight = sum(p["value"] for p in with_ytm)
    by_issuer = _members(positions, _shares(positions, "group", total))
    by_bucket = _shares(positions, "bucket", total)
    breaches = []
    for issuer, share in by_issuer.items():
        if share["share_pct"] > profile["max_issuer_share_pct"]:
            breaches.append(f"{issuer} is {share['share_pct']}% of the portfolio; "
                            f"limit {profile['max_issuer_share_pct']}%")
    for bucket, limit in profile["max_rating_bucket_share_pct"].items():
        share = by_bucket.get(bucket, {"share_pct": 0})["share_pct"]
        if share > limit:
            breaches.append(f"{bucket}-rated bonds are {share}% of the portfolio; limit {limit}%")
    everything = snapshot["holdings"]
    return {
        "as_of": snapshot["as_of"],
        "totals": {
            "current_value": round(total, 2),
            "invested": round(sum(h["invested"] or 0 for h in held), 2),
            "principal_repaid": round(sum(h["principal_repaid"] or 0 for h in everything), 2),
            "interest_net_received": round(sum(h["interest_net_paid"] or 0 for h in everything), 2),
            "tds": round(sum(h["tds_paid"] or 0 for h in everything), 2),
            "weighted_ytm": (round(sum(p["value"] * p["ytm"] for p in with_ytm) / weight, 2)
                             if weight else None)},
        "positions": positions,
        "by_issuer": by_issuer,
        "by_rating_bucket": by_bucket,
        "by_tenure": _shares(positions, "tenure", total),
        "breaches": breaches,
        "unrated": sorted({p["issuer"] for p in positions if p["rating"] is None}),
        "ratings_not_for_this_bond": sorted({p["issuer"] for p in positions
                                             if p["rating_scope"] in ("issuer", "sibling bond")}),
    }


def _table(header, rows):
    lines = ["| " + " | ".join(header) + " |", "|" + "---|" * len(header)]
    lines += ["| " + " | ".join("" if c is None else str(c) for c in row) + " |" for row in rows]
    return "\n".join(lines)


def render_markdown(summary):
    t = summary["totals"]
    parts = [
        "# Wint Wealth portfolio",
        f"As of {summary['as_of']}. Generated by portfolio.py; do not edit by hand.",
        _table(["Current value", "Invested", "Weighted YTM %", "Principal repaid",
                "Interest received (net)", "TDS"],
               [[t["current_value"], t["invested"], t["weighted_ytm"], t["principal_repaid"],
                 t["interest_net_received"], t["tds"]]]),
        "## Positions",
        _table(["Issuer", "ISIN", "Value", "Share %", "YTM %", "Matures", "Months left", "Rating",
                "Rating applies to"],
               [[p["issuer"], p["isin"], p["value"], p["share_pct"], p["ytm"], p["maturity_date"],
                 p["months_left"], p["rating"] or "unrated", p["rating_scope"] or "not recorded"]
                for p in summary["positions"]]),
        "## By issuer group",
        _table(["Issuer or group", "Value", "Share %", "Members"],
               [[k, v["value"], v["share_pct"], ", ".join(v.get("members", []))]
                for k, v in summary["by_issuer"].items()]),
        "## By rating bucket",
        _table(["Bucket", "Value", "Share %"],
               [[k, v["value"], v["share_pct"]] for k, v in summary["by_rating_bucket"].items()]),
        "## By remaining tenure",
        _table(["Tenure", "Value", "Share %"],
               [[k, v["value"], v["share_pct"]] for k, v in summary["by_tenure"].items()]),
        "## Limit breaches",
        "\n".join(f"- {b}" for b in summary["breaches"]) or "None.",
        "## Unrated",
        "\n".join(f"- {i}: no rating recorded in bond-facts.json" for i in summary["unrated"])
        or "None.",
    ]
    return "\n\n".join(parts) + "\n"


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--root")
    args = parser.parse_args(argv)
    root = common.resolve_root(args.root)
    data = common.skill_data_dir(root)
    snapshots = common.dated_files(data, "snapshot-")
    if not snapshots:
        print("No snapshot yet. Run ingest.py reports first.", file=sys.stderr)
        return 1
    try:
        profile = common.load_profile(root)
    except (FileNotFoundError, ValueError) as err:
        print(err, file=sys.stderr)
        return 1
    summary = summarise(common.load_json(snapshots[-1]),
                        bond_facts.load(bond_facts.facts_path(root)), profile)
    with open(os.path.join(data, "PORTFOLIO.md"), "w", encoding="utf-8") as fh:
        fh.write(render_markdown(summary))
    print(json.dumps(summary, indent=2, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    sys.exit(main())
