#!/usr/bin/env python3
"""Keep a dated record of a review, so a past run can be read back later.

    python3 scripts/run_record.py save [--date YYYY-MM-DD] [--root PATH]

Writes data/skill-data/runs/<date>/ from the newest snapshot, listings capture,
bond facts and ledger:

    portfolio.json  cashflows.json  repayment_check.json  diff.json  screen.json
    verdicts.json   the newest verdict per bond
    REVIEW.md       totals, breaches, repayment status, and the verdict table

and refreshes the verdict history at the top of each data/skill-data/bonds/
<issuer>.md note, so a note never shows a verdict the ledger has since replaced.

Run it last, after the verdicts are in the ledger. A second run on the same
date rewrites these files with the current state. It never touches
runs/<date>/analysis.md: that file is for the written reading of the run, which
only a person or the model can supply, and the text below a note's generated
block is left as it was.

The screener's result is recorded only if the listings capture is still fresh;
otherwise screen.json says why it was skipped."""
import argparse
import datetime as dt
import os
import re
import sys

import bond_facts
import cashflows
import common
import diff_snapshots
import portfolio
import rating_ledger
import repayment_check
import screen_listings

START = "<!-- verdicts:start (generated from the ledger by run_record.py; do not edit) -->"
END = "<!-- verdicts:end -->"


def slug(issuer):
    return re.sub(r"[^a-z0-9]+", "-", issuer.lower()).strip("-")


def _cell(value):
    return "" if value is None else str(value).replace("|", "/").replace("\n", " ")


def _table(header, rows):
    lines = ["| " + " | ".join(header) + " |", "|" + "---|" * len(header)]
    lines += ["| " + " | ".join(_cell(c) for c in row) + " |" for row in rows]
    return "\n".join(lines)


def _bond_key(entry):
    return entry["kind"], entry.get("isin") or entry.get("bond_id") or entry["issuer"]


def latest_verdicts(entries):
    """The newest ledger entry for each bond, ordered by kind then issuer."""
    latest = {}
    for entry in entries:
        latest[_bond_key(entry)] = entry
    return sorted(latest.values(), key=lambda e: (e["kind"], e["issuer"], _bond_key(e)[1]))


def _history(entries):
    rows = [[e["at"][:10], e["kind"], e.get("isin") or e.get("bond_id") or "", e["verdict"],
             e["reason"]] for e in sorted(entries, key=lambda e: e["at"], reverse=True)]
    return "\n".join([START, "## Verdict history", "",
                      _table(["Date", "Kind", "Bond", "Verdict", "Deciding reason"], rows), END])


def sync_notes(bonds_dir, entries):
    """Rewrite the generated verdict-history block of every issuer's note from
    the ledger, creating the note if there is none. Returns the paths written."""
    os.makedirs(bonds_dir, exist_ok=True)
    by_issuer = {}
    for entry in entries:
        by_issuer.setdefault(entry["issuer"], []).append(entry)
    written = []
    for issuer, issuer_entries in by_issuer.items():
        path = os.path.join(bonds_dir, slug(issuer) + ".md")
        text = ""
        if os.path.exists(path):
            with open(path, encoding="utf-8") as fh:
                text = fh.read()
        block = _history(issuer_entries)
        if START in text and END in text:
            text = text[:text.index(START)] + block + text[text.index(END) + len(END):]
        elif text.startswith("# "):
            title, _, rest = text.partition("\n")
            text = f"{title}\n\n{block}\n\n{rest.lstrip()}"
        else:
            text = f"# {issuer}\n\n{block}\n\n{text}"
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(text if text.endswith("\n") else text + "\n")
        written.append(path)
    return written


def render_review(date, summary, flows, repay, screen, verdicts):
    totals = summary["totals"]
    by_isin = {v["isin"]: v for v in verdicts if v["kind"] == "holding" and v.get("isin")}
    holdings = []
    for p in summary["positions"]:
        v = by_isin.get(p["isin"])
        holdings.append([p["issuer"], p["isin"], p["value"], p["share_pct"], p["ytm"],
                         p["maturity_date"], p["rating"] or "unrated",
                         p["rating_scope"] or "not recorded",
                         v["verdict"] if v else "none recorded", v["at"][:10] if v else "",
                         v["reason"] if v else ""])
    listing_rows = [[v["issuer"], v.get("bond_id") or "", v["verdict"], v["at"][:10], v["reason"]]
                    for v in verdicts if v["kind"] == "listing"]
    ahead = flows["principal_ahead"]
    overdue = repay.get("overdue", [])
    flags = repay["flags"] + overdue
    parts = [
        f"# Wint Wealth review, {date}",
        f"Generated by run_record.py from the snapshot of {summary['as_of']}. Figures are script "
        "output. The written reading of this run, if any, is in analysis.md beside this file.",
        "## Portfolio",
        _table(["Current value", "Invested", "Weighted YTM %", "Principal repaid",
                "Interest received (net)", "TDS"],
               [[totals["current_value"], totals["invested"], totals["weighted_ytm"],
                 totals["principal_repaid"], totals["interest_net_received"], totals["tds"]]]),
        "## Limit breaches",
        "\n".join(f"- {b}" for b in summary["breaches"]) or "None.",
        "## Holdings and verdicts",
        _table(["Issuer", "ISIN", "Value", "Share %", "YTM %", "Matures", "Rating",
                "Rating applies to", "Verdict", "Verdict date", "Deciding reason"], holdings),
        "## Repayments",
        f"Baseline check: {repay['note']} ({repay['checked']} due payment(s) checked).",
        _table(["Issuer", "ISIN", "Due", "Expected", "Received", "Kind"],
               [[f["issuer"], f["isin"], f["date"], f["expected"], f["received"], f["kind"]]
                for f in flags]) if flags else "No late, short or overdue payment flagged.",
        "## Cash coming back",
        f"Next {flows['idle_cash']['window_days']} days: {flows['idle_cash']['total']} "
        f"(principal {flows['idle_cash']['total_principal']}). "
        f"Next {ahead['window_days']} days, principal only: {ahead['total_principal']}, "
        f"{ahead['share_of_portfolio_pct']}% of the portfolio.",
        _table(["Month", "Principal"], [[m, v] for m, v in ahead["by_month"].items()])
        if ahead["by_month"] else "No principal due in that window.",
        "## Listings",
        (f"Screen skipped: {screen['skipped']}" if "skipped" in screen else
         f"Capture of {screen['captured_at']}: {screen['counts']['shortlisted']} of "
         f"{screen['counts']['listed']} bonds shortlisted. Full result in screen.json."),
        _table(["Issuer", "Bond id", "Verdict", "Date", "Deciding reason"], listing_rows)
        if listing_rows else "No listing verdicts recorded.",
        "## Not verified by a script",
        "\n".join(f"- {line}" for line in (
            [f"Unrated holdings: {', '.join(summary['unrated'])}"] if summary["unrated"] else [])
            + ([f"Rating is the issuer's or a sibling bond's, not this bond's: "
                f"{', '.join(summary['ratings_not_for_this_bond'])}"]
               if summary["ratings_not_for_this_bond"] else [])) or "Nothing flagged.",
    ]
    return "\n\n".join(parts) + "\n"


def save(root, date, now=None):
    data = common.skill_data_dir(root)
    snapshot_paths = common.dated_files(data, "snapshot-")
    if not snapshot_paths:
        raise FileNotFoundError("No snapshot yet. Run ingest.py reports first.")
    snapshots = [common.load_json(p) for p in snapshot_paths]
    current = snapshots[-1]
    profile = common.load_profile(root)
    config = common.load_config()
    facts = bond_facts.load(bond_facts.facts_path(root))
    listings = [common.load_json(p) for p in common.dated_files(data, "listings-")[-2:]]
    entries = rating_ledger.load(rating_ledger.ledger_path(root))

    summary = portfolio.summarise(current, facts, profile)
    start, days = current["as_of"], profile["lookahead_days"]
    flows = {"as_of": start, "upcoming": cashflows.upcoming(current, start, days),
             "monthly": cashflows.monthly(current),
             "idle_cash": cashflows.idle_cash(current, start, days),
             "principal_ahead": cashflows.principal_ahead(
                 current, start, config["reinvestment_horizon_days"]),
             "maturities": cashflows.maturities(current, start, days)}
    repay = repayment_check.check(snapshots, current)
    repay["overdue"] = repayment_check.overdue(current)
    diff = {"holdings": diff_snapshots.diff_holdings(
        snapshots[-2] if len(snapshots) > 1 else None, current)}
    screen = {"skipped": "no listings capture"}
    if listings:
        diff["listings"] = diff_snapshots.diff_listings(
            listings[-2] if len(listings) > 1 else None, listings[-1], config)
        diff["held_issuer_signals"] = diff_snapshots.held_issuer_signals(
            listings[-1], current, facts)
        try:
            screen = screen_listings.screen(listings[-1], current, facts, profile, config,
                                            now or dt.datetime.now(dt.timezone.utc))
        except screen_listings.StaleCapture as err:
            screen = {"skipped": str(err)}
    verdicts = latest_verdicts(entries)

    out = os.path.join(data, "runs", date)
    os.makedirs(out, exist_ok=True)
    for name, content in (("portfolio", summary), ("cashflows", flows),
                          ("repayment_check", repay), ("diff", diff), ("screen", screen),
                          ("verdicts", verdicts)):
        common.write_json(os.path.join(out, name + ".json"), content)
    with open(os.path.join(out, "REVIEW.md"), "w", encoding="utf-8") as fh:
        fh.write(render_review(date, summary, flows, repay, screen, verdicts))
    sync_notes(os.path.join(data, "bonds"), entries)
    return out


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    sub = parser.add_subparsers(dest="command", required=True)
    saver = sub.add_parser("save")
    saver.add_argument("--date")
    saver.add_argument("--root")
    args = parser.parse_args(argv)
    date = args.date or dt.date.today().isoformat()
    try:
        dt.date.fromisoformat(date)
        out = save(common.resolve_root(args.root), date)
    except (FileNotFoundError, ValueError) as err:
        print(f"run_record: {err}", file=sys.stderr)
        return 1
    print(f"run saved: {out}")
    for name in sorted(os.listdir(out)):
        print(f"  {name}")
    if not os.path.exists(os.path.join(out, "analysis.md")):
        print("  (no analysis.md yet: write the reading of this run there)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
